2025-01-16 13:51:32,068 INFO    MainThread:5491 [wandb_setup.py:_flush():68] Current SDK version is 0.19.3
2025-01-16 13:51:32,068 INFO    MainThread:5491 [wandb_setup.py:_flush():68] Configure stats pid to 5491
2025-01-16 13:51:32,068 INFO    MainThread:5491 [wandb_setup.py:_flush():68] Loading settings from /user/ma4177/.config/wandb/settings
2025-01-16 13:51:32,069 INFO    MainThread:5491 [wandb_setup.py:_flush():68] Loading settings from /user/ma4177/Exp_neural/wandb/settings
2025-01-16 13:51:32,069 INFO    MainThread:5491 [wandb_setup.py:_flush():68] Loading settings from environment variables
2025-01-16 13:51:32,070 INFO    MainThread:5491 [wandb_init.py:_log_setup():598] Logging user logs to /user/ma4177/Exp_neural/wandb/run-20250116_135132-dwp7p2b1/logs/debug.log
2025-01-16 13:51:32,071 INFO    MainThread:5491 [wandb_init.py:_log_setup():599] Logging internal logs to /user/ma4177/Exp_neural/wandb/run-20250116_135132-dwp7p2b1/logs/debug-internal.log
2025-01-16 13:51:32,072 INFO    MainThread:5491 [wandb_init.py:init():714] calling init triggers
2025-01-16 13:51:32,072 INFO    MainThread:5491 [wandb_init.py:init():719] wandb.init called with sweep_config: {}
config: {'trainer': {}, 'optimizer': {}, 'nn_architecture': {}}
2025-01-16 13:51:32,073 INFO    MainThread:5491 [wandb_init.py:init():745] starting backend
2025-01-16 13:51:32,286 INFO    MainThread:5491 [wandb_init.py:init():749] sending inform_init request
2025-01-16 13:51:32,292 INFO    MainThread:5491 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-01-16 13:51:32,292 INFO    MainThread:5491 [wandb_init.py:init():764] backend started and connected
2025-01-16 13:51:32,294 INFO    MainThread:5491 [wandb_init.py:init():857] updated telemetry
2025-01-16 13:51:32,308 INFO    MainThread:5491 [wandb_init.py:init():889] communicating run to backend with 90.0 second timeout
2025-01-16 13:51:37,002 ERROR   MainThread:5491 [wandb_init.py:init():918] encountered error: failed to upsert bucket: returned error 403 Forbidden: {"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
2025-01-16 13:51:37,003 ERROR   MainThread:5491 [wandb_init.py:init():1378] error in wandb.init()
Traceback (most recent call last):
  File "/user/ma4177/.conda/envs/exp_neural/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1368, in init
    return wi.init(run_settings)
  File "/user/ma4177/.conda/envs/exp_neural/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 924, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 403 Forbidden: {"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
2025-01-16 13:51:37,012 WARNING MsgRouterThr:5491 [router.py:message_loop():75] message_loop has been closed
